# src/test/resources/application-test.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database  # Replace 'test_database' with your test DB name
    username: root                             # Replace with your MySQL test user
    password: 123@Qaz456                        # Replace with your test password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop                          # Creates tables at startup, drops them after tests
    show-sql: true                                   # Show SQL queries in the console
